# Generated by Django 5.0.2 on 2024-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/static/recipes/images/general/onion_sad.jfif', upload_to='recipes/static/recipes/images'),
        ),
    ]
