# Generated by Django 5.0.2 on 2024-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'fav_recipe', 'verbose_name_plural': 'fav_recipes'},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='updated',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='recipes/static/recipes/images/general/onion_sad.jfif', upload_to='users/static/users/images/'),
        ),
    ]
