# Generated by Django 5.0.2 on 2024-02-23 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista_nombre', models.CharField(max_length=15)),
                ('artista_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('artista_grammys', models.IntegerField(verbose_name='Grammys ganados')),
                ('artista_votos', models.IntegerField(default=0)),
                ('artista_imagen', models.ImageField(upload_to='artistas/')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_nombre', models.CharField(max_length=15)),
                ('genero_imagen', models.ImageField(upload_to='generos/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_nombre', models.CharField(max_length=30)),
                ('album_fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('album_puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('album_imagen', models.ImageField(upload_to='albumes/')),
                ('album_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.artista')),
                ('album_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion_nombre', models.CharField(max_length=30)),
                ('cancion_duracion', models.TimeField(verbose_name='Duración')),
                ('cancion_url', models.URLField()),
                ('cancion_lyrics', models.CharField(max_length=5000)),
                ('cancion_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.album')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='artista_genero',
            field=models.ManyToManyField(to='player.genero'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.artista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
