# Generated by Django 5.0.2 on 2024-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_descripcion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion',
            name='imagen',
        ),
    ]
