# Generated by Django 5.0.2 on 2024-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_remove_descripcion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
